[2022-06-03 16:03:09,946] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ClusterDAG_test.t2 2022-06-03T16:03:03.479402+00:00 [queued]>
[2022-06-03 16:03:10,004] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ClusterDAG_test.t2 2022-06-03T16:03:03.479402+00:00 [queued]>
[2022-06-03 16:03:10,004] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 16:03:10,004] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2022-06-03 16:03:10,004] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 16:03:10,031] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): t2> on 2022-06-03T16:03:03.479402+00:00
[2022-06-03 16:03:10,036] {standard_task_runner.py:51} INFO - Started process 97 to run task
[2022-06-03 16:03:10,040] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ClusterDAG_test', 't2', '2022-06-03T16:03:03.479402+00:00', '--job-id', '146', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/HelloDAG.py', '--cfg-path', '/tmp/tmpz9dwaucl']
[2022-06-03 16:03:10,041] {standard_task_runner.py:76} INFO - Job 146: Subtask t2
[2022-06-03 16:03:10,207] {logging_mixin.py:103} INFO - Running <TaskInstance: ClusterDAG_test.t2 2022-06-03T16:03:03.479402+00:00 [running]> on host slave02
[2022-06-03 16:03:10,422] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ClusterDAG_test
AIRFLOW_CTX_TASK_ID=t2
AIRFLOW_CTX_EXECUTION_DATE=2022-06-03T16:03:03.479402+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-03T16:03:03.479402+00:00
[2022-06-03 16:03:10,422] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-06-03 16:03:10,423] {bash.py:158} INFO - Running command: sleep 1
[2022-06-03 16:03:10,430] {bash.py:169} INFO - Output:
[2022-06-03 16:03:10,452] {bash.py:173} INFO - /root/.bashrc: line 18: zoo-start: command not found
[2022-06-03 16:03:11,454] {bash.py:177} INFO - Command exited with return code 0
[2022-06-03 16:03:11,563] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=ClusterDAG_test, task_id=t2, execution_date=20220603T160303, start_date=20220603T160309, end_date=20220603T160311
[2022-06-03 16:03:11,683] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-06-03 16:03:11,697] {local_task_job.py:118} INFO - Task exited with return code 0
